version: '3.8'

services:
  etherfi-bids-exporter:
    image: a41ventures/etherfi-bids-exporter:${EXPORTER_VERSION:-v0.1.0}
    container_name: etherfi-bids-exporter
    restart: unless-stopped
    environment:
      FETCHING_BIDS_INTERVAL_MINUTES: ${FETCHING_BIDS_INTERVAL_MINUTES:-60}
      EXPORTER_PORT: ${EXPORTER_PORT:-8000}
      API_URL: ${API_URL}
      BIDDER_ADDRESS: ${BIDDER_ADDRESS}
    ports:
      - ${EXPORTER_PORT:-8000}:${EXPORTER_PORT:-8000}